CREATE TABLE IF NOT EXISTS 'users'(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS 'orders'(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    product TEXT NOT NULL,
    description TEXT NOT NULL,
    order_date DATE NOT NULL,
    user_id INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
);
