@URL=http://127.0.0.1:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTc0MDczMTEsInVzZXJfaWQiOjF9.R3mpLQVHDVd4z6c5VJb7jUACV3AJLHJ6nebdPYLFu3g
### Health
GET {{URL}}/health

### Create User
POST {{URL}}/user/registry
Content-Type: application/json

{
    "username": "Henrique",
    "password": "12345"
}

### Login User
POST {{URL}}/user/login
Content-Type: application/json

{
    "username": "Henrique",
    "password": "12345"
}

### Create Orders
POST {{URL}}/orders/1
Content-Type: application/json
Authorization: Bearer {{token}}
uid: 1

{
    "product": "Pokemon Legends",
    "description": "Pokemon Legends AZ"
}
